---
R1 :
    hostname : 192.168.1.35
    groups :
        - local_grp

R2 :
    hostname : 192.168.1.33
    groups :
        - local_grp
R3 :
    hostname : 192.168.1.36
    groups :
        - tacacs_grp
R4 :
    hostname : 192.168.1.34
    groups :
        - tacacs_grp
